# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  myJobVar: "false"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  
- powershell: |
    Write-Host "##vso[task.setvariable variable=myJobVar]true"
  condition: succeeded()

- powershell: |
    Write-Host "Task successful: $(myJobVar)"    
