trigger:  
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0 
        displayName: 'Use Node 18.x'
        inputs:
          versionSpec: '18.x'

      - task: Npm@1
        displayName: 'Npm install packages'
        inputs:
          workingDir: '.'
        
      - task: Gulp@0
        displayName: 'Execute bundle gulp task'
        inputs:
          gulpFile: ./gulpfile.js
          targets: bundle
          arguments: '--ship'

      - task: Gulp@0
        displayName: 'Execute package-solution gulp task'
        inputs:
          targets: 'package-solution'
          arguments: '--ship'  

      - task: CopyFiles@2
        displayName: 'Copy sppkg-file to artifact staging directory'
        inputs:
          Contents: |
            sharepoint/**/*.sppkg        
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
          
      - task: PublishBuildArtifacts@1
        displayName: 'Publish staged artifacts'
        inputs:
          artifactName: 'drop' 

- stage: Deploy
  condition: succeeded('Build')
  jobs:
  - deployment: 'Deploy'
    environment: 'Production environment'
    pool:
      vmImage: 'ubuntu-latest'
    
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: drop
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: NodeTool@0 
            displayName: 'Use Node 22.x'
            inputs:
              versionSpec: '22.x'

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'install @pnp/cli-microsoft365 -g'

          - script: |            
              m365 login # ...

              m365 spo set --url 'https://blimped.sharepoint.com'

              m365 spo app add --filePath '$(System.ArtifactsDirectory)/blimped-hello-world.sppkg' --overwrite
              
              m365 spo app deploy --name 'blimped-hello-world.sppkg' --appCatalogScope 'tenant'
            

